services:
  - type: web
    name: safe-video-downloader
    env: node
    plan: free
    buildCommand: "npm install && pip install yt-dlp ffmpeg"
    startCommand: "node src/server.js"
    healthCheckPath: "/"
    envVars:
      - key: PORT
        value: 3000
      - key: YTDLP_PATH
        value: "yt-dlp"
      - key: PYTHON_PATH
        value: "python3"
      - key: NODE_ENV
        value: "production"
